### PR TITLE
Fix java.lang.IllegalArgumentException in ConnectionListener

### PR DESCRIPTION
**Pull request by jjestrel**
Add check for messagesReceivedDiff instead of messagesReceivedSnapshot for jetty metrics collection

### CODE REVIEW

**Comment by ryanhall07** [comment]
shouldn't there also be a change to gracefully handle exceptions in a finally block and close the connection?

**Comment by mmihic** [comment]
This code doesn't control the lifecycle of the connection; it just monitors metrics

**Comment by jjestrel** [comment]
Are you saying that you want to wrap all of the ConnectionListener code in a try catch?

**Comment by ryanhall07** [comment]
well if Jetty is not going to gracefully handle a listener throwing an exception, then yes. Most likely we could create our own composite listener that does the exception handling for all our custom listeners.

**Comment by mmihic** [comment]
oh woah ok I didn't realize this was the source of the connection leaks. Then definitely yes we should have a wrapper connection listener that handles exceptions.

**Pull request merged**
